#!mast -x Syckfile -x PROFILE .ruby bin lib man qed spec test [A-Z]*
.ruby
bin/regex
lib/regex/command.rb
lib/regex/extractor.rb
lib/regex/package.yml
lib/regex/replacer.rb
lib/regex/string.rb
lib/regex/templates.rb
lib/regex.rb
qed/regex.rdoc
qed/replacer.rdoc
LICENSE
README
HISTORY
VERSION
